version: '2'
services:
  controller:
    build:
      context: ./Controller
      dockerfile: Dockerfile
    container_name: controller
  esrally:
    build:
      context: ./ESRally
      dockerfile: Dockerfile
    container_name: esrally
    volumes:
      - esrallydata:/usr/share/rally/data
  monitoring:
    build:
    context: ./Monitoring
    dockerfile: Dockerfile
    container_name: monitoring
    command:  >
              bin/elasticsearch -Ecluster.name=benchmark-docker-cluster
               -Enetwork.publish_host=10.0.0.253
               -Ediscovery.zen.ping.unicast.hosts=10.0.0.220 
               -Ediscovery.zen.ping_timeout=3s 
               -Ediscovery.zen.minimum_master_nodes=1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - monitoringdata:/usr/share/monitoring/data
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  esrallydata:
    driver: local
  monitoringdata:
    driver: local

