# Elasticsearch Benchmark Dockerfile
# https://github.com/honestbee/docker-esrally

FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.0

RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm
RUN yum -y install python36u
RUN yum -y install python36u-pip
RUN yum -y install python36u-devel

