version: '2'
services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.publish_host="10.0.0.21" 
      - discovery.zen.ping.unicast.hosts="10.0.0.115" 
      - discovery.zen.ping_timeout=3s 
      - discovery.zen.minimum_master_nodes=1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  esdata:
    driver: local

