version: '2'
services:
  esrally:
    build:
      context: esrally
    container_name: esrally
    volumes:
      - esrallydata:/usr/share/rally/data
    stdin_open: true
    tty: true
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://10.0.0.101:9200
    volumes:
      - monitoringdata:/usr/share/kibana/data
volumes:
  esrallydata:
    driver: local
  monitoringdata:
    driver: local

