version: '2'
services:
  esrally:
    build: esrally
    container_name: esrally
    volumes:
      - esrallydata:/usr/share/rally/data
    stdin_open: true
    tty: true
  kibana:
    build: kibana
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://10.0.0.101:9200
    volumes:
      - monitoringdata:/usr/share/kibana/data  
  elasticsearch:
    build: /home/ec2-user/espb/AWS/ESBenchmark
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.publish_host=10.0.0.102
      - discovery.zen.ping.unicast.hosts=10.0.0.101
      - discovery.zen.ping_timeout=3s 
      - discovery.zen.minimum_master_nodes=1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  esrallydata:
    driver: local
  monitoringdata:
    driver: local
  esdata:
    driver: local

